### ISSUE TITLE
能否设置 RSS 投递数为不限制？

### ISSUE THREAD

**Issue by LyonUp** [heqiangflytosky/heqiangflytosky.github.io#1]
最近在阅读您的博客，觉得写的特别好，所以加入了 RSS 源。但是首次拉取文章只能拿到最新的20篇，看了下 hexo 的 feed 配置：
```
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
```
猜测你这里 limit 应该写了20。能否设置成0或者false吗？ (Use 0 or false to show all posts)）
